// packages/testing-library/kitten-lynx/test-fixture/cases/react-example/App.tsx
import { useCallback, useEffect, useState } from '@lynx-js/react';

import './App.css';
import arrow from './assets/arrow.png';
import lynxLogo from './assets/lynx-logo.png';
import reactLynxLogo from './assets/react-logo.png';
import { useFlappy } from './useFlappy.js';

export function App() {
  const [alterLogo, setAlterLogo] = useState(false);
  const [logoY, jump] = useFlappy();

  useEffect(() => {
    console.info('Hello, ReactLynx');
  }, []);

  const onTap = useCallback(() => {
    'background-only';
    setAlterLogo(prevAlterLogo => !prevAlterLogo);
  }, []);

  return (
    <view bindtap={jump}>
      <view className='Background' />
      <view className='App'>
        <view className='Banner'>
          <view
            className='Logo'
            style={{ transform: `translateY(${logoY}px)` }}
            bindtap={onTap}
          >
            {alterLogo
              ? <image src={reactLynxLogo} className='Logo--react' />
              : <image src={lynxLogo} className='Logo--lynx' />}
          </view>
          <text className='Title'>React</text>
          <text className='Subtitle'>on Lynx</text>
        </view>
        <view className='Content'>
          <image src={arrow} className='Arrow' />
          <text className='Description'>Tap the logo and have fun!</text>
          <text className='Hint'>
            Edit<text
              style={{
                fontStyle: 'italic',
                color: 'rgba(255, 255, 255, 0.85)',
              }}
            >
              {' cases/react-example/App.tsx '}
            </text>
            to see updates!
          </text>
        </view>
        <view style={{ flex: 1 }}></view>
      </view>
    </view>
  );
}

// examples/vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from '@lynx-js/vue-runtime'

import './App.css'
import arrow from './assets/arrow.png'
import lynxLogo from './assets/lynx-logo.png'
import vueLogo from './assets/vue-logo.png'
import { useFlappy } from './useFlappy.js'

const alterLogo = ref(false)
const { y: logoY, jump } = useFlappy()

onMounted(() => {
  console.info('Hello, Vue Lynx')
})

function onTap() {
  alterLogo.value = !alterLogo.value
}
</script>

<template>
  <view @tap="jump">
    <view class="Background" />
    <view class="App">
      <view class="Banner">
        <view
          class="Logo"
          :style="{ transform: `translateY(${logoY}px)` }"
          @tap="onTap"
        >
          <image
            :src="alterLogo ? vueLogo : lynxLogo"
            :class="alterLogo ? 'Logo--vue' : 'Logo--lynx'"
          />
        </view>
        <text class="Title">Vue</text>
        <text class="Subtitle">on Lynx</text>
      </view>
      <view class="Content">
        <image :src="arrow" class="Arrow" />
        <text class="Description">Tap the logo and have fun!</text>
        <text class="Hint">
          Edit<text
            :style="{
              fontStyle: 'italic',
              color: 'rgba(255, 255, 255, 0.85)',
            }"
          >{{ ' src/App.vue ' }}</text>to see updates!
        </text>
      </view>
      <view :style="{ flex: 1 }" />
    </view>
  </view>
</template>
