// packages/vue/e2e-lynx/src/App.vue
<!-- Copyright 2025 The Lynx Authors. All rights reserved.
     Licensed under the Apache License Version 2.0 that can be found in the
     LICENSE file in the root directory of this source tree. -->

<!--
  App.vue — SFC root component
  Exercises: interpolation, v-for, dynamic :style/:class, child component, script setup
-->
<script setup lang="ts">
import { ref } from 'vue'
import Counter from './Counter.vue'

const title = ref('Vue 3 × Lynx — SFC Demo')
const history = ref<number[]>([])

function onCounterIncrement(value: number) {
  history.value.push(value)
  // Keep only last 5 entries
  if (history.value.length > 5) history.value.shift()
}
</script>

<template>
  <view :style="{ flex: 1, display: 'flex', flexDirection: 'column', backgroundColor: '#f5f5f5' }">
    <!-- interpolation + dynamic style -->
    <text :style="{ fontSize: 18, fontWeight: 'bold', margin: 16, color: '#111' }">
      {{ title }}
    </text>

    <!-- child component with props and event -->
    <Counter :initial-count="0" @increment="onCounterIncrement" />

    <!-- v-for list rendering -->
    <view v-if="history.length > 0" :style="{ margin: '0 16px' }">
      <text :style="{ fontSize: 13, color: '#555', marginBottom: 4 }">History:</text>
      <view
        v-for="(val, idx) in history"
        :key="idx"
        :style="{
          padding: '2px 8px',
          marginBottom: 2,
          backgroundColor: '#fff',
          borderRadius: 4,
        }"
      >
        <text :style="{ fontSize: 12, color: '#333' }">#{{ idx + 1 }}: {{ val }}</text>
      </view>
    </view>
  </view>
</template>

// packages/genui/a2ui-playground/lynx-src/openui/App.tsx
// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
import {
  OpenUiRenderer,
  createOpenUiLibrary,
  createStreamingParser,
} from '@lynx-js/openui-reactlynx';
import type { ActionEvent, ParseResult } from '@lynx-js/openui-reactlynx';
import { useCallback, useEffect, useMemo, useState } from '@lynx-js/react';

import { OPENUI_SCENARIOS } from './mockData.js';

const mockData = OPENUI_SCENARIOS[0].raw;

export function App() {
  const openUiLibrary = useMemo(() => createOpenUiLibrary(), []);

  const [parseResult, setParseResult] = useState<ParseResult | null>(null);
  const [error, setError] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError('');

    try {
      const streamParser = createStreamingParser(openUiLibrary.toJSONSchema());
      const result = streamParser.push(mockData);
      if (!cancelled) {
        setParseResult(result);
      }
    } catch (e) {
      if (!cancelled) {
        setError(String(e));
      }
    } finally {
      if (!cancelled) {
        setLoading(false);
      }
    }

    return () => {
      cancelled = true;
    };
  }, [openUiLibrary]);

  const onOpenUiAction = useCallback((_event: ActionEvent) => {
    // noop for now
  }, []);

  return (
    <view style={{ width: '100%', height: '100%', backgroundColor: '#fff' }}>
      {error
        ? (
          <view style={{ padding: '12px' }}>
            <text style={{ color: '#c40000' }}>{error}</text>
          </view>
        )
        : null}

      {loading
        ? (
          <view style={{ padding: '12px' }}>
            <text>Loading...</text>
          </view>
        )
        : null}

      {parseResult?.root
        ? (
          <scroll-view scroll-y style={{ height: '100%' }}>
            <OpenUiRenderer
              result={parseResult}
              library={openUiLibrary}
              onAction={onOpenUiAction}
              isStreaming={false}
            />
          </scroll-view>
        )
        : null}
    </view>
  );
}
